### ISSUE TITLE
ValueError: X is an empty array

### ISSUE THREAD

**Issue by zheng325** [fwtan/who_where#4]
Hi sir, I get an error when demo，could you give me some advice, error as follow, and the coco.py need "val2014_filtered_persons.txt", what it contains? Thank you very much. 
Traceback (most recent call last):
  File "tools/demo.py", line 54, in <module>
    retriever.sample(testdb, val_imdb.objdb, mode=0, K=1, show_gt=False)
  File "/mnt/hdd1/zzk/image composition/who_where-master/tools/../lib/models/RetrievalCNN.py", line 83, in sample
    dst_tree = self.build_search_tree(dst_ctxdb, mode)
  File "/mnt/hdd1/zzk/image composition/who_where-master/tools/../lib/models/RetrievalCNN.py", line 72, in build_search_tree
    return BallTree(X, leaf_size=30, metric=cus_distance)
  File "sklearn/neighbors/binary_tree.pxi", line 1068, in sklearn.neighbors.ball_tree.BinaryTree.__init__
ValueError: X is an empty array

**Comment by fwtan** [comment]
Please download the [coco_aux.zip](https://www.dropbox.com/s/fxe6or2zis7f1sc/coco_aux.zip?dl=0) file as well. Please unzip the file to the correct directory as indicated in the instruction.
